<a href="https://colab.research.google.com/github/vrangr-ops/Python-for-Data/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
print ('hello world')

hello world


In [7]:
import numpy as np

arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [8]:
import numpy as np

matrix = np.ones((4, 4))
print(matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
import numpy as np

arr = np.linspace(0, 1, 5)
print(arr)


[0.   0.25 0.5  0.75 1.  ]
