<a href="https://colab.research.google.com/github/vrangr-ops/Python-for-Data/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ('hello world')

hello world


In [ ]:
import numpy as np

arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np

matrix = np.ones((4, 4))
print(matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np

arr = np.linspace(0, 1, 5)
print(arr)


[0.   0.25 0.5  0.75 1.  ]


In [ ]:
#2d array
mat= np.array([[1,2,3,4,5,6,7,8,9]])

print('Whole Matrix:\n',mat)

Whole Matrix:
 [[1 2 3 4 5 6 7 8 9]]


In [ ]:
mat2= np.array([[1,2,3,4,5,6,7,8,9,10]])

print ('First 5 elements:', arr[0:5])

First 5 elements: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
import numpy as np

arr = np.arange(1, 11)   # numbers 1–10
first_five = arr[:5]     # slice first 5
print(arr)
print(first_five)


[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]


In [ ]:
import numpy as np

matrix = np.ones((4, 4))
first_two_rows = matrix[:2]
print(first_two_rows)

sub_matrix = matrix[2:, 2:]
print(sub_matrix)




[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]]
